name: 'Carbon Aware Scheduler'
description: 'Schedules a job to run when the carbon intensity is low'
inputs:
  region:
    required: true
    default: 'eastus'
  template-paths:
    description: 'Path to template of job to be scheduled'
    required: true
    default: 'templates/template.yml'
  end-time:
    description: 'End time for job scheduling'
    default: ''
  estimated-job-length:
    description: 'Estimated length of job in minutes'
    default: 10
  output-path:
    description: 'Path for output of scheduled jobs'
    default: '.github/workflows/'

outputs:
  schedules-workflows:
    description: 'Scheduled workflows'
  scheduled-time:
    description: 'Time that workflows have been scheduled to run'

runs:
  using: 'node20'
  main: 'dist/index.js'
